Repository norlab-ulaval/libpointmatcher-server, pull requests merged in 2024-05, with the labels that each got.

#141 fix anonymous
  api/db/leaderboard_mongo.py
  api/leaderboard/leaderboard_entry.py
Labels: enhancement, refactor

#142 Task110/restructure home auth routes
  web/libpointmatcher-server-interface/package-lock.json
  web/libpointmatcher-server-interface/package.json
  web/libpointmatcher-server-interface/src/App.vue
  web/libpointmatcher-server-interface/src/api.js
  web/libpointmatcher-server-interface/src/components/layout/Navbar.vue
  web/libpointmatcher-server-interface/src/components/upload/DragAndDrop.vue
  web/libpointmatcher-server-interface/src/router/index.js
  web/libpointmatcher-server-interface/src/stores/authStore.js
  web/libpointmatcher-server-interface/src/stores/counter.js
  web/libpointmatcher-server-interface/src/views/AuthView.vue
Labels: enhancement

#143 update of the readmes
  README.md
  api/README.md
  db/README.md
  doc/README.md
  libpointmatcher/README.md
Labels: documentation
