Repository norlab-ulaval/libpointmatcher-server, pull requests merged in 2024-02, with the labels that each got.

#20 first readme
  README.md
Labels: documentation

#22 User sample
  api/db/__init__.py
  api/db/mongo.py
  api/db/users_mongo.py
  api/dependencies.py
  api/main.py
  api/mongo.py
  api/routers/__init__.py
  api/routers/example.py
  api/user/__init__.py
  api/user/user.py
  api/user/user_controller.py
  api/user/user_repo.py
Labels: documentation, enhancement

#31 small fixes
  api/auth/auth.py
  api/requirements.txt
  api/routers/auth.py
Labels: bug

#30 Added redis cache to docker compose
  api/auth/__init__.py
  api/interface/__init__.py
  docker-compose.yml
Labels: enhancement

#34 Docker web
  api/main.py
  docker-compose.yml
  web/libpointmatcher-server-interface/Dockerfile
  web/libpointmatcher-server-interface/package-lock.json
  web/libpointmatcher-server-interface/package.json
  web/libpointmatcher-server-interface/src/api.js
Labels: enhancement

#43 Move stuff to controller
  api/auth/auth.py
  api/auth/token.py
  api/db/users_mongo.py
  api/interface/interface_models.py
  api/main.py
  api/routers/auth.py
  api/user/user_controller.py
  api/user/user_repo.py
Labels: enhancement

#44 done!
  api/auth/token.py
  api/db/mongo.py
  api/db/users_mongo.py
  api/user/user.py
  api/user/user_controller.py
Labels: enhancement

#50 corrected the api
  api/db/users_mongo.py
  api/interface/interface_models.py
  api/user/user_controller.py
  api/user/user_repo.py
  web/libpointmatcher-server-interface/src/assets/base.css
Labels: enhancement

#62 validation_backend
  api/db/users_mongo.py
  api/user/user_controller.py
  api/user/user_repo.py
  api/user/user_validation.py
Labels: enhancement

#65 Finalize SignUp Feature
  web/libpointmatcher-server-interface/src/App.vue
  web/libpointmatcher-server-interface/src/api.js
  web/libpointmatcher-server-interface/src/assets/base.css
  web/libpointmatcher-server-interface/src/components/Auth/SignIn.vue
  web/libpointmatcher-server-interface/src/components/Auth/SignUp.vue
  web/libpointmatcher-server-interface/src/components/SignIn.vue
  web/libpointmatcher-server-interface/src/components/SignUp.vue
  web/libpointmatcher-server-interface/src/components/icons/IconEyeOpen.vue
  web/libpointmatcher-server-interface/src/components/icons/IconEyeSlash.vue
  web/libpointmatcher-server-interface/src/components/ui/ToastNotification.vue
  web/libpointmatcher-server-interface/src/router/index.js
  web/libpointmatcher-server-interface/src/views/AuthView.vue
Labels: enhancement
